<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.iona.fuse.cxf.container</groupId>
    <artifactId>it-soa-container-distribution</artifactId>
    <packaging>pom</packaging>
    <name>Tandoori Container Distribution</name>
    <version>2.1.0-fuse-SNAPSHOT</version>

    <parent>
        <groupId>com.iona.fuse.cxf.container</groupId>
        <artifactId>it-soa-container</artifactId>
        <version>2.1.0-fuse-SNAPSHOT</version>
    </parent>

    <dependencies>
        <!-- fake dependencies -->
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>

        <!--  Real dependencies  -->
        <dependency>
            <groupId>com.iona.fuse.cxf.container</groupId>
            <artifactId>it-soa-container-rt</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>

            <plugin>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>2.1</version>
                <dependencies>
                    <dependency>
                        <groupId>com.iona.buildtools</groupId>
                        <artifactId>codestyle</artifactId>
                        <version>${codestyle.version}</version>
                    </dependency>
                </dependencies>
                <configuration>
                    <descriptorRefs>
                        <descriptorRef>distribution</descriptorRef>
                    </descriptorRefs>
                </configuration>
                <executions>
                    <execution>
                        <id>package-extras</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

        </plugins>
    </build>


</project>