<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.iona.fuse.cxf</groupId>
    <artifactId>fuse-extras</artifactId>
    <packaging>pom</packaging>
    <name>FUSE Extras</name>
    <version>2.0.2.3-fuse</version>
    <url>http://open.iona.com/products/fuse-services-framework/</url>

    <parent>
        <groupId>org.apache.cxf</groupId>
        <artifactId>cxf</artifactId>
        <version>2.0.2.3-fuse</version>
    </parent>

    <licenses>
        <license>
            <name>FUSE Services Framework v.2.0 License Agreement</name>
            <url>http://open.iona.com/downloads/license-agreements/fuse-services-framework-v-2-0-license-agreement/</url>
            <distribution>repo</distribution>
        </license>
    </licenses>
    <organization>
        <name>IONA Technologies, PLC</name>
        <url>http://www.iona.com/</url>
    </organization>

    <modules>
        <module>parent</module>
        <module>container</module> 
    </modules>
</project>
